const nodemailer = require('nodemailer')
const KafkaAvro = require('kafka-node-avro');

let transport = nodemailer.createTransport({
  host: "smtp.mailtrap.io",
  port: 2525,
  auth: {
    user: "7844df47fa40d0", //generated by Mailtrap
    pass: "c6f48d3aa14ca6" //generated by Mailtrap
  }
})


const Settings  = {
  "kafka" : {
    "kafkaHost" : "localhost:9092"
  },
  "schema": {
    "registry" : "http://localhost:8081"
  }
};

let recommendations = {
  "ba6a8d26-b505-45e4-a83f-bf2c31fd7846": "Suria KLCC",
  "db0728e2-d865-47a5-b65c-d99af4272756": "Setapak Central",
  "01e12f03-6969-4c77-b027-59a462b24fae": "Plaza Arkadia"
}

KafkaAvro.init(Settings).then(kafka => {
    let consumer = kafka.addConsumer("demo_parking");

    consumer.on('message', message => {
      console.log(message)
      console.log(recommendations[message.value.carpark_id])

      let user = message.value.user_id
      let mall = recommendations[message.value.carpark_id]

      let mailOptions = generateMailOptions(user, mall)

      sendMail(mailOptions)
    })
  }, error => {
    // something wrong happen
  })

let generateMailOptions = (user, mall) => {return {
    from: '"Confluent Demo" <jlaw@jlaw-demo.com>',
    to: 'jlaw@confluent.io',
    subject: '',
    html: `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
          <html xmlns="http://www.w3.ord/1999/xhtml">

          <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title></title>
          </head>

          <style>
            /* regular CSS styles go here */

             body {
               color: #2a2a2a;
               font-family: Arial, sans-serif;
               font-size: 18px;
               width:100% !important;
               -webkit-text-size-adjust:100%;
               -ms-text-size-adjust:100%;
               margin:0;
               padding:0;
               margin-bottom:20px;
               line-height:18px;
             }

             .generosity {
               color: #535964;
             }

             h1, h2, h3, h4, h5 {
               font-weight: bold;
             }

             h1, h2, h3, h4, h5, p {
               margin: 0;
               padding: 0;
             }

             h1 {
               font-size: 24px;
               line-height: 32px;
             }

             .generosity h1 {
               font-size: 30px;
               line-height: 40px
             }

             h2 {
               font-size: 20px;
               line-height: 26px;
             }

             h3 {
               font-size: 18px;
               line-height: 26px;
             }

             h4 {
               font-size: 16px;
               line-height: 26px;
             }

             h5 {
               font-size: 14px;
               line-height: 20px;
             }

             p {
               font-size: 16px;
               line-height: 22px;
             }

             .header-section {
               padding: 60px 50px 50px;
             }

             .header-section p {
               font-size: 18px;
               line-height: 26px;
             }

             .bullet {
               color: #2a2a2a;
               font-weight: bold;
               font-size: 18px;
               -webkit-text-size-adjust:100%;
               -ms-text-size-adjust:100%;
               margin-right:20px;
               margin-left: 0;
               margin-top: 0;
               margin-bottom: 0 !important;
               padding: 0;
               line-height:28px;
             }

             .generosity .bullet {
               color: #535964;
             }

             .sub-bullet p {
               color: #2a2a2a;
               font-size: 18px;
               margin:0;
               margin-right:40px;
               margin-left:35px;
               margin-top: 0;
               margin-bottom:15px;
               padding:0;
               line-height:18px;
             }

             .generosity .sub-bullet p {
               color: #535964;
             }


             .sub-bullet img {
               margin-right:15px !important;
               margin-left:0px !important;
             }

             a {
               color: #eb1478;
               text-decoration: none;
             }

             .generosity a {
               color: #FA6950;
             }

             .generosity a.pc-cta {
               background-color: #FA6950;
               font-size: 18px;
               line-height: 46px;
               border-radius: 4px;
               line-height: 50px;
               padding: 5px 45px;
               text-transform: uppercase;
             }

             .generosity a.cta {
               background-color: #FA6950;
               font-size: 18px;
               line-height: 46px;
               border-radius: 4px;
               line-height: 50px;
               padding: 5px 45px;
             }

             a.cta, a.pc-cta {
               background-color: #eb1478;
               color: #ffffff;
               display: inline-block;
               font-family: sans-serif;
               font-size: 18px;
               line-height: 46px;
               text-align: center;
               text-decoration: none;
               -webkit-text-size-adjust: none;
               font-weight: bold;
               padding: 5px 50px;
               white-space: nowrap;
             }

             a.cta {
               text-transform: uppercase;
             }

             a.pc-cta {
               border-radius: 3px;
             }

             .section-image {
               margin: 40px 0;
             }

             ol {
               list-style-position: inside;
               margin: 0;
               padding: 0;
             }

             ul {
               list-style-position: inside;
               margin: 0;
               padding: 0;
             }

             li {
               font-size: 18px;
               line-height: 28px;
               margin: 18px 10px;
             }

             li > a {
               font-weight: bold;
             }


             table.description p {
               margin-bottom: 18px;
             }


             p#call-out-headline {
               font-size: 22px;
               line-height: 32px;
               margin: 18px 40px 0px 40px;
               padding: 0;
               font-weight: bold;
             }

             p.call-out {
               margin: 0 40px;
             }

             div.call-out {
               border-left:1px solid #DDDDDD;
               margin: 0 40px 21px;
               padding-left: 20px;
             }

             div.horizontal-rule {
               border-bottom: 1px solid #DDDDDD;
               margin: 27px 0;
             }

             table.footer p {
               line-height: 18px;
             }

             table.footer a {
               color: #2a2a2a;
             }

             span.yshortcuts {
               color: #06486e !important;
               background-color: none !important;
               border: none !important;
             }

             span.yshortcuts:hover {
               color: #06486e !important;
               background-color: none !important;
               border: none !important;
             }

             span.yshortcuts:active {
               color: #06486e !important;
               background-color: none !important;
               border: none !important;
             }

             span.yshortcuts:focus {
               color: #06486e !important;
               background-color: none !important;
               border: none !important;
             }

             .ExternalClass {
               width: 100%;
             }

             .applelinks a {
               text-decoration: none;
               color: #333333;
             }

             .hidedesk table {
               display: none !important;
             }
             table.contenttable {
               width: 600px;
               align: center;
             }
             table, td {
               border-collapse: collapse;
             }

             p.header {
               color: #eb1478;
               font-size: 24px;
             }

             .gogenta {
               color: #eb1478; }

             .profile-image {
               padding: 5px 5px 5px 0;
             }

             .individual {
               font-size: 20px;
               font-weight: bold;
             }

             .individual-title {
               padding: 5px;
               font-size: 25px;
             }

             .subheader-text {
               font-size: 20px;
               line-height: 26px;
             }

             .social-button {
               color: #fff;
               text-transform: uppercase;
               font-weight: bold;
             }

             .social-button td:last-child {
               padding-right: 20px;
               padding-left: 15px;
             }

             .social-button-life {
               color: #fff;
               font-weight: bold;
             }

             .social-button-life td:last-child {
               padding-right: 30px;
             }

             .contribution-table-label {
               font-size: 14px;
               color: #6a6a6a;
               width: 190px;
               padding: 7px 0 0 0;
             }

             .contribution-table-value {
               font-size: 14px;
               font-weight: bold;
               padding: 7px 0 0 0;
             }

             #fb-email-header {
               padding: 0 0 20px;
             }

             .contribution-total-row .contribution-table-label {
               padding-top: 12px;
               font-size: 16px;
               font-weight: bold;
             }

             .contribution-total-row .contribution-table-value {
               padding-top: 12px;
               font-size: 16px;
             }

             #fb-email-campaign-title {
               color: #2a2a2a;
               font-size: 16px;
               margin:0;
               padding:0;
               line-height:26px;
             }

             #fb-email-campaign-tagline {
               color: #2a2a2a;
               font-size: 16px;
               margin:0;
               padding:0;
               line-height:26px;
             }

             hr {
               display: block;
               height: 1px;
               border: 0;
               border-top: 1px solid #DDDDDD;
               margin: 37px 0 30px;
               padding: 0;
               align: left;
             }

             #callout-name {
               font-size: 24px;
               margin-bottom: 20px;
             }

             #callout-header {
               margin-bottom: 30px;
             }

             #callout-text {
               font-size: 1.5em;
               line-height: 38px;
               margin-bottom: 40px;
             }

             #campaign-name {
               font-weight: bold;
             }

             .complete-my-campaign-btn {
               background-color: #eb1478;
               color: #ffffff;
               display: inline-block;
               font-family: sans-serif;
               font-size: 22px;
               font-weight: bold;
               line-height: 40px;
               padding: 20px 0;
               text-align: center;
               text-decoration: none;
               width: 380px;
               -webkit-text-size-adjust:none;
             }

             #day1-body-items {
               list-style-type: none;
             }

             .new-project-bullet {
               width: 50px;
             }

             .new-project-bullet-desc {
               padding-left: 20px;
               line-height: 26px;
             }

             .day1-item-header {
               font-weight: bold;
             }

             .new-project-item {
               padding-bottom: 20px;
             }

             .black-link-text a:link {
               color: #2a2a2a;
               text-decoration: none;
             }
             .black-link-text a:visited {
               color: #2a2a2a;
               text-decoration: none;
             }
             .black-link-text a:hover {
               color: #2a2a2a;
               text-decoration: none;
             }
             .black-link-text a:active {
               color: #2a2a2a;
               text-decoration: none;
             }

             .gogenta-link-text a:link {
               color: #2a2a2a;
               text-decoration: none;
             }
             .gogenta-link-text a:visited {
               color: #2a2a2a;
               text-decoration: none;
             }
             .gogenta-link-text a:hover {
               color: #2a2a2a;
               text-decoration: none;
             }
             .gogenta-link-text a:active {
               color: #2a2a2a;
               text-decoration: none;
             }

             .life-icon-header {
               margin-top: 50px;
               margin-bottom: 20px;
             }

             .reload-grey-section {
               background-color: #f5f5f5;
             }

             .column-icon {
               width: 60px;
               height: 60px;
             }
          </style>

          <body class="perks " style="color: #2a2a2a; font-family: Arial, sans-serif; font-size: 18px; width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; line-height: 18px; margin: 0 0 20px; padding: 0;">
            <div style="background-color: #eae9ea;">
              <!--[if mso]>
              <v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
                  <v:fill type="tile" color="#eae9ea"></v:fill>
              </v:background><![endif]-->
            </div>
            <table height="100%" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#eae9ea" style="border-collapse: collapse;">
              <tr>
                <td valign="top" align="center" style="border-collapse: collapse;">
                  <table width="600" cellspacing="0" cellpadding="0" border="0" class="main" style="border-collapse: collapse; margin-left: 30px; margin-right: 30px;">
                    <tr>
                      <td align="left" class="min_width" style="border-collapse: collapse; width: 600px;">

                        <!-- BODY SECTION -->

                        <table width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="border-collapse: collapse; margin-top: 10px;" class="">
                          <tr>
                            <td align="left" style="border-collapse: collapse;">

                              <table width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse: collapse;">
                                <tr style="margin: 0; padding: 0;">
                                  <td align="center" style="border-collapse: collapse; border-spacing: 0; padding: 50px;">


                                    <div style="margin-bottom: 30px; text-align: left;" align="left">
                                      <a href="https://google.com.sg" utm_content="igg-header-logo" utm_medium="email" style="color: #eb1478; text-decoration: none;">
                                        <img alt="" class="logo" src="https://assets.confluent.io/m/1661ef5e4ff82d3d/original/20200122-PNG-web-dev-logo-denim.png" style="display: block; border: none;" width="225">
                                      </a>
                                    </div>

                                    <p style="font-size: 22px; line-height: 22px; margin: 0; padding: 0;">Hello ${user},</p>

                                    <div style="text-align: left;" align="left">
                                      <p style="font-size: 20px; line-height: 28px; margin: 20px 0 0; padding: 0;">
                                        We have an offer for you! Get 50% off while shopping at ${mall}.
                                      </p>
                                    </div>

                                    <p style="font-size: 20px; line-height: 22px; margin: 0; padding: 0;">
                                      <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuaW5kaWVnb2dvLmNvbS9hY2NvdW50cy9jb25maXJtYXRpb24_Y29uZmlybWF0aW9uX3Rva2VuPW9CQTEyZEhZc2Z3Nmd3dG9aWXNMJmk9YTNrMA/57221e21fc2383c94d8b4585B0b9fb18d" style="margin-top: 40px; color: #ffffff; text-decoration: none; display: inline-block; font-family: sans-serif; font-size: 20px; line-height: 46px; text-align: center; -webkit-text-size-adjust: none; font-weight: bold; white-space: nowrap; text-transform: uppercase; background-color: #1c3464; padding: 5px 50px;">Start Shopping Now!</a>
                                    </p>

                                    <div style="width: 100px; margin: 35px 0px; border: 1px solid #e9e9e9;"></div>

                                    <p style="font-size: 20px; line-height: 22px; margin: 0; padding: 0;">
                                      Sincerely,
                                    </p>

                                    <p style="font-size: 22px; font-weight: bold; line-height: 22px; margin: 10px 0 0; padding: 0;">
                                      The Confluent Demo Team
                                    </p>


                                  </td>
                                </tr>
                              </table>

                            </td>
                          </tr>
                        </table>


                        <table width="100%" cellspacing="0" cellpadding="0" border="0" class="footer" style="border-collapse: collapse;">
                          <tr>
                            <td align="center" class="footer" style="border-collapse: collapse; padding: 30px;">
                              <p style="font-size: 13px; font-family: Arial, sans-serif; color: #000001; line-height: 18px; margin: 0; padding: 0;">
                                <a class="footer-link" target="_blank" href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuaW5kaWVnb2dvLmNvbS9zdXBwb3J0L2ZvcnVtcw/57221e21fc2383c94d8b4585B5753b706" style="color: #2a2a2a; text-decoration: none;">Customer Happiness Center</a>                      | <a class="footer-link" target="_blank" href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuaW5kaWVnb2dvLmNvbS9leHBsb3JlP2ZpbHRlcl9xdWljaz1wb3B1bGFyX2FsbA/57221e21fc2383c94d8b4585B7c6079c2" style="color: #2a2a2a; text-decoration: none;">Trending Campaigns</a>                      | <a class="footer-link" target="_blank" href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cDovL2dvLmluZGllZ29nby5jb20vYmxvZy9jYXRlZ29yeS9hbm5vdW5jZW1lbnRz/57221e21fc2383c94d8b4585B6bafb74f" style="color: #2a2a2a; text-decoration: none;">Recent news</a>                      | <a class="footer-link" target="_blank" href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuaW5kaWVnb2dvLmNvbS9pbmRpdmlkdWFscy8xMzkzNzczMC9yZWRpcmVjdF9mcm9tX2VtYWlsP3RpbWU9MTQ2MTg1MzcyOSZ0b2tlbj03YjMwNDI0MWJiMzY0MGUwMmU5OGY4ZjdiNDhjODBjNTU2NGI2Yzli/57221e21fc2383c94d8b4585Be55e5cc1"
                                  style="color: #2a2a2a; text-decoration: none;">Email Preference Center</a>
                              </p>
                              <table width="200" cellspacing="0" cellpadding="0" border="0" style="border-collapse: collapse; margin: 30px 0;">
                                <tr>
                                  <td align="right" width="30" style="border-collapse: collapse;">
                                    <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL0luZGllZ29nbw/57221e21fc2383c94d8b4585B97d948ae" style="color: #000001; text-decoration: none;"><img src="https://email-media.s3.amazonaws.com/indiegogo/assets/facebook.png" width="25" style="display: block; border: none;"></a>
                                  </td>
                                  <td align="right" width="30" style="border-collapse: collapse;">
                                    <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly90d2l0dGVyLmNvbS9pbmRpZWdvZ28/57221e21fc2383c94d8b4585B78f03d1b" style="color: #000001; text-decoration: none;"><img src="https://email-media.s3.amazonaws.com/indiegogo/assets/twitter.png" width="25" style="display: block; border: none;"></a>
                                  </td>
                                  <td align="right" width="30" style="border-collapse: collapse;">
                                    <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly9wbHVzLmdvb2dsZS5jb20vK2luZGllZ29nbw/57221e21fc2383c94d8b4585B6e55e11e" style="color: #000001; text-decoration: none;"><img src="https://email-media.s3.amazonaws.com/indiegogo/assets/gplus.png" width="25" style="display: block; border: none;"></a>
                                  </td>
                                  <td align="right" width="30" style="border-collapse: collapse;">
                                    <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cDovL2ZlZWRzLmZlZWRidXJuZXIuY29tL0luZGllZ29nb0Jsb2c/57221e21fc2383c94d8b4585B74b26c1f" style="color: #000001; text-decoration: none;"><img src="https://email-media.s3.amazonaws.com/indiegogo/assets/rss.png" width="25" style="display: block; border: none;"></a>
                                  </td>
                                  <td align="right" width="30" style="border-collapse: collapse;">
                                    <a href="http://link.indiegogo.com/click/57221e226e4adcdb6f8b5c08/aHR0cHM6Ly93d3cuaW5kaWVnb2dvLmNvbS9jb250YWN0L3F1ZXN0aW9ucw/57221e21fc2383c94d8b4585B31767c7b" style="color: #000001; text-decoration: none;"><img src="https://email-media.s3.amazonaws.com/indiegogo/assets/mail.png" width="25" style="display: block; border: none;"></a>
                                  </td>
                                </tr>
                              </table>
                              <p style="font-size: 13px; font-family: Arial, sans-serif; color: #000001; line-height: 18px; margin: 0; padding: 0;">This email was sent to jlaw@confluent.io.</p>
                              <p style="font-size: 13px; font-family: Arial, sans-serif; color: #000001; line-height: 18px; margin: 0; padding: 0;">Confluent Demo · 965 Demo Street, 6th Floor · Singapore</p>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </body>

          </html>`
}}

let sendMail = (mailOptions) => {
  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      return console.log(error);
    }
    console.log('Message sent: %s', info.messageId)
  })
}
