# Vehicle Queries

CREATE TABLE vehicle_table
(
  id string primary key,
  state string,
  deliveryCode string,
  lat double,
  long double,
  destLat double,
  destLong double,
  warehouseLat double,
  warehouseLong double,
  temperature double,
  tirePressure double
)
WITH (KAFKA_TOPIC='vehicles',
VALUE_FORMAT='AVRO',
KEY_FORMAT='KAFKA');

CREATE TABLE QUERYABLE_VEHICLE_TABLE
WITH (
  KAFKA_TOPIC='QUERYABLE_VEHICLE_TABLE',
  PARTITIONS=6,
  REPLICAS=3
)
AS SELECT * FROM VEHICLE_TABLE EMIT CHANGES;

CREATE STREAM vehicle_stream ( id string key, state string, deliveryCode string, lat double, long double, destLat double, destLong double, warehouseLat double, warehouseLong double, temperature double, tirePressure double ) WITH (KAFKA_TOPIC='vehicles', VALUE_FORMAT='AVRO', KEY_FORMAT='KAFKA');

# Orders Queries

CREATE STREAM purchases_stream
(
  id string key,
  name string,
  email string,
  address string,
  order string,
  order_total double
)
WITH (KAFKA_TOPIC='purchases',
VALUE_FORMAT='AVRO',
KEY_FORMAT='KAFKA');

CREATE STREAM PURCHASES_STREAM_MASKED WITH (KAFKA_TOPIC='PURCHASES_STREAM_MASKED', PARTITIONS=6, REPLICAS=3) AS SELECT
  PURCHASES_STREAM.ID ID,
  MASK(PURCHASES_STREAM.NAME) MASKED_NAME,
  MASK(PURCHASES_STREAM.EMAIL) MASKED_EMAIL,
  MASK(PURCHASES_STREAM.ADDRESS) MASKED_ADDRESS,
  PURCHASES_STREAM.ORDER ORDER,
  PURCHASES_STREAM.ORDER_TOTAL ORDER_TOTAL
FROM PURCHASES_STREAM PURCHASES_STREAM
EMIT CHANGES;

CREATE TABLE PURCHASES_TABLE ( id string primary key, name string, email string, address string, order string, order_total double ) WITH (KAFKA_TOPIC='purchases', VALUE_FORMAT='AVRO', KEY_FORMAT='KAFKA');

CREATE TABLE QUERYABLE_PURCHASES_TABLE WITH (KAFKA_TOPIC='QUERYABLE_PURCHASES_TABLE', PARTITIONS=6, REPLICAS=3) AS SELECT * FROM PURCHASES_TABLE PURCHASES_TABLE EMIT CHANGES;

CREATE TABLE ORDER_TRACKER WITH (KAFKA_TOPIC='ORDER_TRACKER', PARTITIONS=6, REPLICAS=3) AS SELECT P.ID ORDER_ID, LATEST_BY_OFFSET(V.ID) VEHICLE_ID, LATEST_BY_OFFSET(V.STATE) STATE, LATEST_BY_OFFSET(V.LAT) LAT, LATEST_BY_OFFSET(V.LONG) LONG, LATEST_BY_OFFSET(V.DESTLAT) DESTLAT, LATEST_BY_OFFSET(V.DESTLONG) DESTLONG, LATEST_BY_OFFSET(ROUND(GEO_DISTANCE(CAST(V.LAT as DOUBLE), cast(V.LONG as DOUBLE), cast(V.DESTLAT as DOUBLE), cast(V.DESTLONG as DOUBLE), 'KM'), 2)) DISTANCE_FROM_DESTINATION, LATEST_BY_OFFSET(ROUND(GREATEST(ABS(V.LAT - V.DESTLAT), ABS(V.LONG - V.DESTLONG)) / (0.5 / 10 / 10) * 2, 2)) ETA_SECONDS FROM VEHICLE_STREAM V JOIN QUERYABLE_PURCHASES_TABLE P ON ((V.DELIVERYCODE = P.ID)) GROUP BY P.ID EMIT CHANGES;
